### PR TITLE
Delegate timed_out? and status_message

### PR DESCRIPTION
**Pull request by aquint**
This exposes the timeout method and status message from Typhoeus::Response to NxtHttpClient::Error

### CODE REVIEW

**Review by nsommer — APPROVED** [review]
👍

**Review by AkihikoITOH — APPROVED** [review]
👍

**Review by getand — APPROVED** [review]

**Comment by getand** [comment]
@aquint can you maybe also mention in readme.

**Comment by aquint** [comment]
> @aquint can you maybe also mention in readme.

Ahh good point! Added.

**Pull request merged**
